export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
export const FETCH_BLOOD = "FETCH_BLOOD";
export const LANGUAGE ="LANGUAGE"
export const FETCH_DRUGS = "FETCH_DRUGS"
export const FETCH_BLOOD_DISTANCE = "FETCH_BLOOD_DISTANCE"
export const OPEN = "OPEN";
export const FETCH_NEWS = "FETCH_NEWS"